import Head from "next/head";
import { GiNightSky } from "react-icons/gi";
import { AiFillLinkedin, AiFillGithub, AiFillHtml5 } from "react-icons/ai";
import { FaNodeJs } from "react-icons/fa";
import { DiPostgresql, DiCss3 } from "react-icons/di";
import { GrReactjs } from "react-icons/gr";
import { TbBrandNextjs } from "react-icons/tb";
import { SiFirebase, SiTailwindcss, SiVercel, SiRedux } from "react-icons/si";
import Image from "next/image";
import devAli from "../../public/images/devAli.png";
import insta from "../../public/images/insta.png";
import savoirsApp from "../../public/images/savoirs.png";
import LinkedIn from "../../public/images/linkedin_logo.png";
import Gmail from "../../public/images/Gmail-Logo.png";
import Logo from "../../public/images/logo_noir.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio Alizéa Massé</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 dark:text-gray-300">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-2xl font-BebasNeue dark:text-gray-300">
              Développer par Alizéa Massé
            </h1>
            <ul className="flex items-center">
              <li>
                <GiNightSky
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-4xl dark:text-gray-300"
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-red-700 to-red-400 dark:from-blue-900 dark:to-blue-600  text-white px-4 py-2 rounded-md ml-8 "
                  href="/CV_ALIZEA_MASSE.pdf"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  CV
                </a>
              </li>
            </ul>
            <div className=" h-45 w-96 mx-auto block ">
              <Image src={devAli} />
            </div>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl text-red-700 dark:text-blue-400 font-medium">
              Alizéa Massé
            </h2>
            <h3 className="text-2xl py-2">Développeuse Web</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-300">
              Mon premier emploi m'a orienté vers le monde de la programmation.
              Ce qui m’intéresse le plus dans ce domaine est la
              pluridisciplinarité, le fait qu’il y ait toujours quelque chose à
              découvrir, à apprendre. Mon objectif est maintenant de pouvoir
              mettre mes compétences en pratique au service de projets d'avenir
              !
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-24 text-gray-600 dark:text-gray-300">
            <a
              href="https://www.linkedin.com/in/aliz%C3%A9amass%C3%A9/"
              target="_blank"
            >
              <AiFillLinkedin className="cursor-pointer" />
            </a>
            <a href="https://github.com/Alizea-Masse" target="_blank">
              <AiFillGithub className="cursor-pointer" />
            </a>
          </div>
        </section>

        <section className="text-gray-600 body-font dark:text-gray-300">
          <div className="container py-24 mx-auto">
            <div className="flex flex-wrap -m-4">
              <div className="p-4 md:w-1/3">
                <div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden w-72">
                  <Image
                    className="lg:h-48 md:h-36 w-full object-cover object-center"
                    src={savoirsApp}
                    alt="blog"
                  />
                  <div className="p-6">
                    <h2 className="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">
                      PROJET
                    </h2>
                    <h1 className="title-font text-lg font-medium text-gray-900 mb-3 dark:text-gray-300">
                      Transmission des savoirs
                    </h1>
                    <div className="leading-relaxed mb-3">
                      Réalisation de la partie back-end d'un site de petites
                      annonces. <br /> <br />
                      {/* icons */}
                      <div className="flex gap-3">
                        <FaNodeJs className="text-5xl" />
                        <DiPostgresql className="text-5xl" />
                        <GrReactjs className="text-5xl" />
                        <AiFillHtml5 className="text-5xl" />
                        <DiCss3 className="text-5xl" />
                      </div>
                      <br />- Création d'une API REST avec Node.js et Express.js{" "}
                      <br /> <br />
                      - Création d'une base de données avec PostgreSQL <br />{" "}
                      <br />
                      - Création de l'authentification avec JWT <br /> <br />
                      - Back-end d'un formulaire de contact avec nodemailer,
                      xoauth et GoogleAPI <br /> <br />
                      - Écriture de tests grâce à Jest <br /> <br />- Aide sur
                      le front-end avec React.js
                    </div>
                    <div className="flex items-center flex-wrap ">
                      <a
                        href="https://savoirs.surge.sh/"
                        target="_blank"
                        className="text-blue-500 inline-flex items-center md:mb-2 lg:mb-0"
                      >
                        Visiter le site
                        <svg
                          className="w-4 h-4 ml-2"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          strokeWidth="2"
                          fill="none"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          <path d="M5 12h14"></path>
                          <path d="M12 5l7 7-7 7"></path>
                        </svg>
                      </a>
                    </div>
                  </div>
                </div>
              </div>

               <div className="p-4 md:w-1/3">
                <div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden w-72">
                  <Image
                    className="lg:h-48 md:h-32 w-43 object-fill object-center"
                    src={Logo}
                    alt="blog"
                  />
                  <div className="p-6">
                    <h2 className="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">
                      PROJET
                    </h2>
                    <h1 className="title-font text-lg font-medium text-gray-900 mb-3 dark:text-gray-300">
                      Rêve Réalité Production
                    </h1>
                    <div className="leading-relaxed mb-3">
                      Réalisation complète d'un site web afin de présenter les spectacles de magie d'une boite de production bordelaise. <br /> <br />
                      {/* icons */}
                      <div className="flex gap-3">
                        <FaNodeJs className="text-5xl" />
                        <GrReactjs className="text-5xl" />
                        <AiFillHtml5 className="text-5xl" />
                        <DiCss3 className="text-5xl" />
                      </div>
                      <br /> <br />
                      - Création d'une interface responsive avec HTML/CSS et Styled Components
                      <br /> <br />
                      - Dynamisation du site et mise place d'un routeur avec REACT
                      <br /> <br />
                      - Création d'annimation grace à la bibliothèque AOS
                      <br /> <br />
                      - Back-end d'un formulaire de contact avec nodemailer,
                      xoauth et GoogleAPI 
                    </div>
                    <div className="flex items-center flex-wrap ">
                      <a
                        href="https://reve-realite.surge.sh/"
                        target="_blank"
                        className="text-blue-500 inline-flex items-center md:mb-2 lg:mb-0"
                      >
                        Visiter le site
                        <svg
                          className="w-4 h-4 ml-2"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          strokeWidth="2"
                          fill="none"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          <path d="M5 12h14"></path>
                          <path d="M12 5l7 7-7 7"></path>
                        </svg>
                      </a>
                    </div>
                  </div>
                </div>
              </div>

              <div className="p-4 md:w-1/3">
                <div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden w-72">
                  <Image
                    className="lg:h-48 md:h-36 w-full object-cover object-center"
                    src={LinkedIn}
                    alt="blog"
                  />
                  <div className="p-6">
                    <h2 className="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">
                      PROJET
                    </h2>
                    <h1 className="title-font text-lg font-medium text-gray-900 mb-3 dark:text-gray-300">
                      LinkedIn Copy
                    </h1>

                    <p className="leading-relaxed mb-3">
                      <div className="flex gap-3">
                        <AiFillHtml5 className="text-5xl" />
                        <DiCss3 className="text-5xl" />
                        <GrReactjs className="text-5xl" />
                        <SiFirebase className="text-5xl" />
                        <SiRedux className="text-5xl" />
                      </div>
                      <br />
                      - Création d'une interface en html/css. <br /> <br />
                      - Création d'une interface dynamique et affichage
                      conditionnel avec ReactJS, utilisation du state ainsi que
                      de logique dans le JSX <br /> <br />
                      - Utilisation de Redux afin de gérer le store de
                      l'application <br /> <br />
                      - Création d'une base de données avec Firebase afin de
                      gérer les posts <br /> <br />
                      - Création de l'authentification avec Firebase <br />{" "}
                      <br />
                      - Déploiement de l'application sur Firebase <br /> <br />
                    </p>
                    <div className="flex items-center flex-wrap ">
                      <a
                        href="https://linkedin-clone-2ac24.web.app/"
                        target="_blank"
                        className="text-blue-500 inline-flex items-center md:mb-2 lg:mb-0"
                      >
                        Visiter le site
                        <svg
                          className="w-4 h-4 ml-2"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          strokeWidth="2"
                          fill="none"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          <path d="M5 12h14"></path>
                          <path d="M12 5l7 7-7 7"></path>
                        </svg>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <div className="p-4 md:w-1/3">
                <div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden w-72">
                  <Image
                    className="lg:h-48 md:h-36 w-full object-cover object-center"
                    src={Gmail}
                    alt="blog"
                  />
                  <div className="p-6">
                    <h2 className="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">
                      PROJET
                    </h2>
                    <h1 className="title-font text-lg font-medium text-gray-900 mb-3 dark:text-gray-300">
                      Gmail Copy
                    </h1>

                    <p className="leading-relaxed mb-3">
                      <div className="flex gap-3">
                        <AiFillHtml5 className="text-5xl" />
                        <DiCss3 className="text-5xl" />
                        <GrReactjs className="text-5xl" />
                        <SiFirebase className="text-5xl" />
                        <SiRedux className="text-5xl" />
                      </div>
                      <br />
                      - Création d'une interface en html/css. <br /> <br />
                      - Création d'une interface dynamique et affichage
                      conditionnel avec ReactJS, utilisation du state ainsi que
                      de logique dans le JSX <br /> <br />
                      - Utilisation de Redux afin de gérer le store de
                      l'application <br /> <br />
                      - Création d'une base de données avec Firebase afin de
                      gérer les mails <br /> <br />
                      - Création de l'authentification avec Firebase et Google comme provider  <br />{" "}
                      <br />
                      - Déploiement de l'application sur Firebase <br /> <br />
                    </p>
                    <div className="flex items-center flex-wrap ">
                      <a
                        href="https://copy-99077.web.app/"
                        target="_blank"
                        className="text-blue-500 inline-flex items-center md:mb-2 lg:mb-0"
                      >
                        Visiter le site
                        <svg
                          className="w-4 h-4 ml-2"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          strokeWidth="2"
                          fill="none"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          <path d="M5 12h14"></path>
                          <path d="M12 5l7 7-7 7"></path>
                        </svg>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <div className="p-4 md:w-1/3">
                <div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden w-72">
                  <Image
                    className="lg:h-48 md:h-36 w-full object-cover object-center"
                    src={insta}
                    alt="blog"
                  />
                  <div className="p-6">
                    <h2 className="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">
                      PROJET
                    </h2>
                    <h1 className="title-font text-lg font-medium text-gray-900 mb-3 dark:text-gray-300">
                      Instagram Copy
                    </h1>
                    <p className="leading-relaxed mb-3">
                      <a
                        className="bg-slate-200 rounded-sm p-1 dark:text-gray-500"
                        href="https://www.youtube.com/watch?v=a6Xs2Ir40OI"
                        target="_blank"
                      >
                        Tutoriel
                      </a>{" "}
                      réalisé dans le but de parfaire mes connaissances,
                      découvrir de nouvelles technologies ainsi que témoigner de
                      mon adaptabilité. Il m'est possible d'expliquer toutes les
                      étapes du code.{" "}
                    </p>
                    <div className="flex gap-3">
                      <TbBrandNextjs className="text-5xl" />
                      <GrReactjs className="text-5xl" />
                      <SiFirebase className="text-5xl" />
                      <AiFillHtml5 className="text-5xl" />
                      <SiTailwindcss className="text-5xl" />
                      <SiVercel className="text-5xl" />
                    </div>
                    <br />
                    - Création d'une interface responsive, mobile first avec
                    tailwind CSS <br /> <br />
                    - Création d'une interface dynamique et affichage
                    conditionnel avec ReactJS, utilisation du state ainsi que de
                    logique dans le JSX <br /> <br />
                    - Utilisation de Recoil afin de gérer le store de
                    l'application <br /> <br />
                    - Création d'une base de données avec Firebase afin de gérer
                    les likes, les commentaires et les posts <br /> <br />
                    - Prise en main du framework React, NextJs. <br /> <br />
                    - Création de l'authentification avec Google comme provider
                    grâce à NextAuth <br /> <br />
                    - Déploiement de l'application sur Vercel et gestion des
                    variables d'environnement <br /> <br />
                    <div className="flex items-center flex-wrap">
                      <a
                        href="https://instagram-copy-alpha.vercel.app/"
                        target="_blank"
                        className="text-blue-500 inline-flex items-center md:mb-2 lg:mb-0"
                      >
                        Visiter le site
                        <svg
                          className="w-4 h-4 ml-2"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          strokeWidth="2"
                          fill="none"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          <path d="M5 12h14"></path>
                          <path d="M12 5l7 7-7 7"></path>
                        </svg>
                      </a>
                    </div>
                  </div>
                </div>
              </div>

              
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
